#!/usr/bin/env python3
"""
Vector Blind RAG - Challenge Server
Provides the query oracle for the encrypted RAG system.

Usage: python server.py [port]
Default port: 8080

Requires: server_key.json (generated by generate.py, KEEP SECRET)
          challenge_data.json (generated by generate.py, public)
"""

import json
import sys
from http.server import HTTPServer, BaseHTTPRequestHandler
from socketserver import ThreadingMixIn


# ─── Matrix arithmetic over Z_p ──────────────────────────────────────────────

def mat_vec_mul(vec, mat, p):
    """Row vector (1 x k) times matrix (k x m) modulo p. Returns row vector (1 x m)."""
    if not mat:
        return []
    m = len(mat[0])
    result = [0] * m
    for i, vi in enumerate(vec):
        if vi == 0:
            continue
        row = mat[i]
        for j in range(m):
            result[j] = (result[j] + vi * row[j]) % p
    return result


# ─── Query encryption (THE VULNERABLE FUNCTION) ──────────────────────────────

def encrypt_query(q, M1_inv, M2_inv, p):
    """Encrypt a query vector for ASPE-based search.

    Note: query vector is not split before encryption.
    This is a deliberate simplification over the full ASPE protocol
    where q would be randomly split as q = q1 + q2 and each half
    encrypted separately with M1^{-1} and M2^{-1}.
    """
    t1 = mat_vec_mul(q, M1_inv, p)
    t2 = mat_vec_mul(q, M2_inv, p)
    return t1, t2


# ─── Data loading ────────────────────────────────────────────────────────────

def load_data():
    """Load challenge data and server secret keys."""
    try:
        with open("challenge_data.json", "r") as f:
            challenge = json.load(f)
    except FileNotFoundError:
        print("ERROR: challenge_data.json not found. Run generate.py first.")
        sys.exit(1)

    try:
        with open("server_key.json", "r") as f:
            keys = json.load(f)
    except FileNotFoundError:
        print("ERROR: server_key.json not found. Run generate.py first.")
        sys.exit(1)

    p = int(challenge["p"])
    n = challenge["n"]
    database = challenge["database"]

    M1_inv = [[int(x) for x in row] for row in keys["M1_inv"]]
    M2_inv = [[int(x) for x in row] for row in keys["M2_inv"]]

    return p, n, database, M1_inv, M2_inv


# ─── HTTP Handler ────────────────────────────────────────────────────────────

class ThreadingHTTPServer(ThreadingMixIn, HTTPServer):
    """HTTP server with threading support for concurrent connections."""
    daemon_threads = True


class RequestHandler(BaseHTTPRequestHandler):
    """Handles /query (POST), /database (GET), and / (GET) endpoints."""

    # These are set by the server after loading data
    P = None
    N = None
    DATABASE = None
    M1_INV = None
    M2_INV = None

    def log_message(self, fmt, *args):
        """Suppress default access log to stderr."""
        pass

    def _send_json(self, status, data):
        body = json.dumps(data).encode()
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Access-Control-Allow-Origin", "*")
        self.end_headers()
        self.wfile.write(body)

    def _send_error(self, status, message):
        self._send_json(status, {"error": message})

    def do_GET(self):
        if self.path == "/" or self.path == "/health":
            self._send_json(200, {
                "status": "ok",
                "service": "Vector Blind RAG Query Oracle",
                "n": self.N,
            })
        elif self.path == "/database":
            with open("challenge_data.json", "r") as f:
                db = json.load(f)
            self._send_json(200, db)
        else:
            self._send_error(404, "not found")

    def do_POST(self):
        if self.path != "/query":
            self._send_error(404, "not found")
            return

        try:
            content_len = int(self.headers.get("Content-Length", 0))
            body = json.loads(self.rfile.read(content_len))
        except (ValueError, json.JSONDecodeError):
            self._send_error(400, "invalid JSON body")
            return

        q_raw = body.get("q")
        if q_raw is None or not isinstance(q_raw, list):
            self._send_error(400, f"missing 'q' field; must be a list of {self.N} integers")
            return
        if len(q_raw) != self.N:
            self._send_error(400, f"expected q of length {self.N}, got {len(q_raw)}")
            return

        try:
            q = [int(x) for x in q_raw]
        except (ValueError, TypeError):
            self._send_error(400, "q must contain valid integers")
            return

        t1, t2 = encrypt_query(q, self.M1_INV, self.M2_INV, self.P)
        self._send_json(200, {
            "t_q": [[str(x) for x in t1], [str(x) for x in t2]],
        })

    def do_OPTIONS(self):
        self.send_response(204)
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")
        self.end_headers()


# ─── Main ────────────────────────────────────────────────────────────────────

def main():
    p, n, database, M1_inv, M2_inv = load_data()

    RequestHandler.P = p
    RequestHandler.N = n
    RequestHandler.DATABASE = database
    RequestHandler.M1_INV = M1_inv
    RequestHandler.M2_INV = M2_inv

    port = int(sys.argv[1]) if len(sys.argv) > 1 else 8080
    server = ThreadingHTTPServer(("0.0.0.0", port), RequestHandler)
    print(f"Vector Blind RAG oracle listening on port {port}")
    print(f"  GET  /          - health check")
    print(f"  GET  /database  - download encrypted database")
    print(f"  POST /query      - submit query vector, get encrypted token")

    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nShutting down.")
        server.shutdown()


if __name__ == "__main__":
    main()
